language: swift # or objective-c
osx_image: xcode11
script:
  - xcodebuild -scheme OZChattingUI-Example -workspace Example/OZChattingUI.xcworkspace -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone Xs,OS=12.1' -configuration Release ONLY_ACTIVE_ARCH=YES -enableCodeCoverage YES test
after_success:
  - bash <(curl -s https://codecov.io/bash) -t 8cd20cd4-e9a6-4729-8357-1f5a72058a1e
